### ISSUE TITLE
Downstream processing and segmentation visualization

### ISSUE THREAD

**Issue by TatianaSezin** [Sanofi-Public/enact-pipeline#9]
Hi guys,

just finished generating our first Visium HD data and was very excited to read about ENACT.
I tried to run the output from our HD Visium results in human skin using ENACT. These were the parameters we used:

segmentation: True
bin_to_geodataframes: True
bin_to_cell_assignment: True
cell_type_annotation: True
seg_method: stardist
patch_size: 4000
bin_representation: polygon
bin_to_cell_method: weighted_by_cluster
cell_annotation_method: celltypist
cell_typist_model: Adult_Human_Skin.pkl
use_hvg: True
n_hvg: 1000
n_clusters: 4

We obtained 6 patches. Is there a way to control the number of patches that are generated? Is there a way to visualize the segmentation results? May you please suggest how one should use the ouput from ENACT to continue visualizing the annotated clusters in SquidPy?

Thank you so much in advance for any input and your great support so far!

**Comment by AlbertPlaPlanas** [comment]
Hi Tatiana!

For the first question, the _patch_size: 4000_ parameter will determine the number of patches you generate. The bigger the patch size, the fewer the output patches. We need to break the image to patches due to memory isssues (if you have enough memory & processing power you could increae the patch size until you get a single patch).

For the sequestion question, the easiest way to visualize your outcomes would be through TissUUmaps ( https://tissuumaps.github.io/installation/ ) where you can (1) load the WSI image and then (2) load the resulting csv or h5ad as markers. In this way you'll see the centroids of your segmented cells (and if you group them by cell_type, you'll also see their type)
I see it may be a good idea to write a short tutorial on how to load the data there, we'll eventually add it to the docs.
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/fb2a0243-1635-4784-9c33-262413d304bb">

For the squidpy question, I'll let my colleague @Mena-SA-Kamel answer it once he is back from a deserved autumn break.

**Comment by TatianaSezin** [comment]
Hi Albert, 

thank you so much for this quick reply and your great help. I will give it a try. My end goal is to integrate several datasets so I was wondering if @Mena-SA-Kamel has experience with multiple Anndata integration in squidpy with Visium HD? 
thanks again for your support!
Tatiana

**Comment by Mena-SA-Kamel** [comment]
Hi Tatiana, 

We made a new ENACT release which now enables the generation of a .tmap project file for visualizing the labelled cells on TissUUmaps. The instructions are provided [here](https://github.com/Sanofi-Public/enact-pipeline/tree/main?tab=readme-ov-file#visualizing-results-on-tissuumaps). 

Regarding the Anndata integration in Squidpy, here is an example of running SquidPy's neighbourhood enrichment analysis on the output AnnData file that ENACT generates (cells_adata.h5)

```
import anndata as ad
import squidpy as sq

adata = ad.read('<path_to_anndata>/cells_adata.h5', backed='r')
sq.gr.spatial_neighbors(adata)
sq.gr.nhood_enrichment(adata, cluster_key="cell_type")
```

To integrate multiple Anndata objects into a single object, you can use `anndata.concat`
`adata_pooled = ad.concat([adata_1, adata_2], join="outer")`

Hope this helps.
Mena

**Comment by Mena-SA-Kamel** [comment]
Closing this issue. Current version of ENACT now generates necessary files to visualize results on Tissuumaps. Feel free to re-open the issue if you have other questions. Thanks again for raising this issue.

**Comment by TatianaSezin** [comment]
Hi Mena,

thank you very much for this additional information and your help regarding
the data integration. We will surely give it a try!

All the best,
Tatiana
